In [4]:
"""
@author:nickhuang1996
"""
import torch
 
rectangle_height = 3
rectangle_width = 3
inputs = torch.randn(rectangle_height, rectangle_width)
for i in range(rectangle_height):
    for j in range(rectangle_width):
        inputs[i] = i * torch.ones(rectangle_width)
'''
inputs and its transpose
-->inputs   =   tensor([[0., 0., 0.],
                        [1., 1., 1.],
                        [2., 2., 2.]])
-->inputs_t =   tensor([[0., 1., 2.],
                        [0., 1., 2.],
                        [0., 1., 2.]])
'''
print("inputs:\n", inputs)
print("inputs.t():",inputs.t())
inputs_t = inputs.t()  # t就是转制
print("inputs_t:\n", inputs_t)
'''
inputs_t @ inputs_t    [[0., 1., 2.],       [[0., 1., 2.],          [[0., 3., 6.]
                    =   [0., 1., 2.],   @    [0., 1., 2.],     =     [0., 3., 6.]
                        [0., 1., 2.]]        [0., 1., 2.]]           [0., 3., 6.]]
'''
 
'''a, b, c and d = 1 * inputs + 1 * (inputs_t @ inputs_t)'''
a = torch.addmm(input=inputs, mat1=inputs_t, mat2=inputs_t)
b = inputs.addmm(mat1=inputs_t, mat2=inputs_t)
c = torch.addmm(input=inputs, beta=1, mat1=inputs_t, mat2=inputs_t, alpha=1)
d = inputs.addmm(beta=1, mat1=inputs_t, mat2=inputs_t, alpha=1)
'''e and f = 1 * inputs + 1 * (inputs_t @ inputs_t)'''
e = torch.addmm(inputs, inputs_t, inputs_t)
f = inputs.addmm(inputs_t, inputs_t)
'''1 * inputs + 1 * (inputs_t @ inputs_t)'''
g = inputs.addmm(1, inputs_t, inputs_t)
'''2 * inputs + 1 * (inputs_t @ inputs_t)'''
g2 = inputs.addmm(2, inputs_t, inputs_t)
'''h = 1 * inputs + 1 * (inputs_t @ inputs_t)'''
h = inputs.addmm(1, 1, inputs_t, inputs_t)
'''h12 = 1 * inputs + 2 * (inputs_t @ inputs_t)'''
h12 = inputs.addmm(1, 2, inputs_t, inputs_t)
'''h21 = 2 * inputs + 1 * (inputs_t @ inputs_t)'''
h21 = inputs.addmm(2, 1, inputs_t, inputs_t)
print("a:\n", a)
print("b:\n", b)
print("c:\n", c)
print("d:\n", d)
 
print("e:\n", e)
print("f:\n", f)
 
print("g:\n", g)
print("g2:\n", g2)
 
print("h:\n", h)
print("h12:\n", h12)
print("h21:\n", h21)
print("inputs:\n", inputs)
'''inputs = 1 * inputs - 2 * (inputs @ inputs_t)'''
'''
inputs @ inputs_t       [[0., 0., 0.],       [[0., 1., 2.],          [[0., 0., 0.]
                    =    [1., 1., 1.],   @    [0., 1., 2.],     =     [0., 3., 6.]
                         [2., 2., 2.]]        [0., 1., 2.]]           [0., 6., 12.]]
'''
inputs.addmm_(1, -2, inputs, inputs_t)  # In-place
print("inputs:\n", inputs)

inputs:
 tensor([[0., 0., 0.],
        [1., 1., 1.],
        [2., 2., 2.]])
inputs.t(): tensor([[0., 1., 2.],
        [0., 1., 2.],
        [0., 1., 2.]])
inputs_t:
 tensor([[0., 1., 2.],
        [0., 1., 2.],
        [0., 1., 2.]])
a:
 tensor([[0., 3., 6.],
        [1., 4., 7.],
        [2., 5., 8.]])
b:
 tensor([[0., 3., 6.],
        [1., 4., 7.],
        [2., 5., 8.]])
c:
 tensor([[0., 3., 6.],
        [1., 4., 7.],
        [2., 5., 8.]])
d:
 tensor([[0., 3., 6.],
        [1., 4., 7.],
        [2., 5., 8.]])
e:
 tensor([[0., 3., 6.],
        [1., 4., 7.],
        [2., 5., 8.]])
f:
 tensor([[0., 3., 6.],
        [1., 4., 7.],
        [2., 5., 8.]])
g:
 tensor([[0., 3., 6.],
        [1., 4., 7.],
        [2., 5., 8.]])
g2:
 tensor([[ 0.,  3.,  6.],
        [ 2.,  5.,  8.],
        [ 4.,  7., 10.]])
h:
 tensor([[0., 3., 6.],
        [1., 4., 7.],
        [2., 5., 8.]])
h12:
 tensor([[ 0.,  6., 12.],
        [ 1.,  7., 13.],
        [ 2.,  8., 14.]])
h21:
 tensor([[ 0.,  3.,  6.],
     

In [3]:
inputs.t()

tensor([[  0.,   1.,   2.],
        [  0.,  -5., -34.],
        [  0.,  13., 122.]])

In [5]:
x = torch.randn(4,3)
y = torch.chunk(x,4,dim = 0)

In [7]:
len(y)

4

In [9]:
y[0].shape

torch.Size([1, 3])

In [12]:
z = x.unbind(0)

In [13]:
len(z)

4

In [15]:
z[0].shape

torch.Size([3])

In [16]:
x = torch.randn(512,135,135)

In [18]:
torch.softmax(x, dim = -1).shape

torch.Size([512, 135, 135])

In [19]:
batch_size = 512
seq_len = 135
feature_dim = 400
q = torch.randn(batch_size, 1, feature_dim)
k = torch.randn(batch_size, seq_len,feature_dim)
v = torch.randn(batch_size, seq_len,feature_dim)


In [20]:
z = torch.bmm(q,k.transpose(1,2))

In [21]:
z.shape

torch.Size([512, 1, 135])