In [1]:
import numpy as np

### 直接np.abs加一个问号运行就可以起到help的效果了

In [2]:
np.abs?

Call signature:  np.abs(*args, **kwargs)
Type:            ufunc
String form:     <ufunc 'absolute'>
File:            d:\pycharmprojects\conda_envs\torch\lib\site-packages\numpy\__init__.py
Docstring:      
absolute(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Calculate the absolute value element-wise.

``np.abs`` is a shorthand for this function.

Parameters
----------
x : array_like
    Input array.
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For oth

### 参数是矩形的shape

In [3]:
np.random.random((2,3))

array([[0.2191011 , 0.92671669, 0.84318754],
       [0.82542721, 0.73212772, 0.18729975]])

### 单位矩阵(三阶)

In [5]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### diag是对角矩阵，单位矩阵和对角矩阵都是方阵

In [6]:
np.diag((1,2,3))

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

### save成txt的格式

#### 参数是X和fname,注意X是大写的X，fname是filename的缩写

In [7]:
np.savetxt(X = np.diag((1,2,3)),fname = 'temp.txt')

In [8]:
np.loadtxt('temp.txt')

array([[1., 0., 0.],
       [0., 2., 0.],
       [0., 0., 3.]])

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### (end - start)/(space-1)

In [12]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

### x必须是一个一维的数组

In [20]:
x = np.random.random(23)

In [21]:
np.random.choice(x,size = (2,3))

array([[0.13029576, 0.60421368, 0.36295007],
       [0.07498091, 0.36295007, 0.60421368]])

#### 对应元素相乘就是element wise product

In [22]:
y = np.random.random(23)

In [23]:
x * y

array([0.39247418, 0.34784506, 0.12055701, 0.37154259, 0.16351923,
       0.11302179, 0.10718917, 0.14138107, 0.32527984, 0.23138149,
       0.26744654, 0.06591411, 0.02759418, 0.00447372, 0.10416146,
       0.01722869, 0.43104199, 0.26620978, 0.55923243, 0.12230492,
       0.01757479, 0.16334049, 0.01436074])

In [24]:
np.multiply(x,y)

array([0.39247418, 0.34784506, 0.12055701, 0.37154259, 0.16351923,
       0.11302179, 0.10718917, 0.14138107, 0.32527984, 0.23138149,
       0.26744654, 0.06591411, 0.02759418, 0.00447372, 0.10416146,
       0.01722869, 0.43104199, 0.26620978, 0.55923243, 0.12230492,
       0.01757479, 0.16334049, 0.01436074])

#### np.dot就是对应的矩阵的相乘

#### 函数作用于array对象的话也是用的广播机制，就是每个函数作用在每个元素上面

#### 矩阵变换
* reshape是返回副本
* resize是在本身上做改变
* ravel是本身改变-展平
* flatten是返回副本-展平

In [28]:
x = np.random.random((2,3))

In [30]:
x

array([[0.59549754, 0.50784464, 0.63795032],
       [0.16609255, 0.57487497, 0.09902215]])

* 按列展开，F应该是行展开为false的意思

In [29]:
x.ravel('F')

array([0.59549754, 0.16609255, 0.50784464, 0.57487497, 0.63795032,
       0.09902215])

In [32]:
z = x.ravel()

In [33]:
z

array([0.59549754, 0.50784464, 0.63795032, 0.16609255, 0.57487497,
       0.09902215])

In [35]:
x.flatten()

array([0.59549754, 0.50784464, 0.63795032, 0.16609255, 0.57487497,
       0.09902215])

#### np.append()和np.concatenate，np.stack都是合并，都有axis这个参数，看你要按行还是按列合并了
* append和concatenate的作用一样，好像是concatenate不怎么占用空间而append占用空间，他们两个都是不改变维度个数的
* stack的话是会改变维度个数的

#### ufunc是universal function的简称

#### 广播机制的规则是
* shape的维度个数向最多的维度个数看齐，不够的就要补1，补1的话是在前面的维度进行补1
* 每个矩阵最后都扩充成所有要处理的矩阵里面每个维度的最大值
* 两个矩阵对应的维度值要么相等要么其中一个为1才可以