In [1]:
import torch

In [2]:
import torch.nn as nn

In [3]:
from torch.nn import utils as nn_utils

In [4]:
batch_size = 2

In [10]:
max_length = 3
hidden_size = 2
n_layers = 1
tensor_in = torch.FloatTensor([[1,2,3],[1,0,0]])

In [11]:
tensor_in.shape

torch.Size([2, 3])

In [12]:
tensor_in = tensor_in.resize_(2,3,1)

In [13]:
tensor_in.shape

torch.Size([2, 3, 1])

In [14]:
tensor_in

tensor([[[1.],
         [2.],
         [3.]],

        [[1.],
         [0.],
         [0.]]])

In [15]:
seq_len = [3,1]

In [16]:
pack = nn_utils.rnn.pack_padded_sequence(tensor_in, seq_len, batch_first = True)

In [21]:
pack.data.shape

torch.Size([4, 1])

* [参考链接](https://zhuanlan.zhihu.com/p/161972223)
* PackedSequence对象里面的batch_sizes是每个时间步骤对应的batch大小
* sorted_indices就是对输入lengths排序后的索引(也就是说它会自动排好序)
* unsorted_indices 是用来将排序数据恢复到原始顺序的索引
* 在pack_padded_sequence中，enforce_sorted默认设置为True，也就是说输入的batch数据要事先按照长度排序，才能输入，实际上，更简单的方式是，将其设置为False，从上面的代码中也可以看出，Pytorch会自动给我们做排序。
* 也就是说enforce_sorted设置为False的话，pack_padded_sequence方法就会自动帮我们排好序

In [22]:
pack

PackedSequence(data=tensor([[1.],
        [1.],
        [2.],
        [3.]]), batch_sizes=tensor([2, 1, 1]), sorted_indices=None, unsorted_indices=None)

In [25]:
nn_utils.rnn.pad_packed_sequence(pack, batch_first=True)

(tensor([[[1.],
          [2.],
          [3.]],
 
         [[1.],
          [0.],
          [0.]]]),
 tensor([3, 1]))

#### 现在这个是没有按照长度排好序的

In [26]:
# input_tensor shape：batch_size=2,time_step=3,dim=1
input_tensor = torch.FloatTensor([[4, 0, 0], [5, 6, 0]]).resize_(2, 3, 1)
seq_lens = torch.IntTensor([1, 2])
x_packed = nn_utils.rnn.pack_padded_sequence(input_tensor, seq_lens, batch_first=True, enforce_sorted=False)

In [31]:
x_packed

PackedSequence(data=tensor([[5.],
        [4.],
        [6.]]), batch_sizes=tensor([2, 1]), sorted_indices=tensor([1, 0]), unsorted_indices=tensor([1, 0]))

* 返回的data里面的部分是每个time_step依次输出来的，也就我先输出第一样本的第一个time_step的值，再输出第二个样本的第一个time_step的值，直到把所有的样本的第一个time_step的值都输出来以后才去输出第二个time_step的值

In [35]:
import torch.nn.functional as F

In [39]:
x = torch.randn(2,3, 2)

* dim的是哪个维度，哪个维度加起来的和就是1

In [41]:
F.softmax(x, dim = 1)

tensor([[[0.4710, 0.9405],
         [0.4627, 0.0383],
         [0.0664, 0.0212]],

        [[0.2669, 0.2945],
         [0.6290, 0.4887],
         [0.1041, 0.2169]]])