#### nn.functional 和 nn.Module其实功能上是一样的，只是Module会自动提取可学习的参数，而functional 更像是纯函数
#### 两种功能相同且性能上面没有太大的区别
#### 像卷积层，全连接层，dropout 层这些含有可学习的参数层就使用nn.Module
#### 而softmax, 激活函数，池化层这些由于不含有可学习参数，所以就可以使用nn.functional 
#### torch.untils.data 里面有Dataloader, Dataloader就是包含了batch的东西

#### transform - torchvision 上的
* torchvision.transform.Compose([])是用来装多个transform的函数的
* Normalize是每个通道的全局平均值和方差Normalize([m1,m2,m3],[n1,n2,n3])
* 如果已经有一个数据的话，那么download参数就设置为False就好了，要不就设置为True
* 一般nn.Sequential都是将两个两个的layer放在一起的，比如一个linear一个batchnorm这样
* max会返回两个值，一个是value, 一个是index下角标

In [1]:
import torch

In [2]:
x = torch.randn(2,3)

In [6]:
x

tensor([[-1.3288,  0.5707, -1.8041],
        [ 0.2446,  0.5754,  1.5342]])

In [4]:
value, index = x.max(dim = 0)

In [5]:
index

tensor([1, 1, 1])

* torch.nn.Squential+OrderedDict来给每一层命名
* OrderedDict是collections里面的，也就说这个dict是有记忆顺序的，key不同顺序的话就代表是不一样的dict
* nn.Module的话需要实例化以后才能使用
* nn.functional 的话不用实例就可以直接使用了

In [18]:
from collections import OrderedDict

In [19]:
class Net(torch.nn.Module):
    def __init__(self):
        super(Net,self).__init__()
        self.conv = torch.nn.Sequential(
        OrderedDict([
            ("conv1",torch.nn.Conv1d(3,32,3,1,1)),
            ("relu1",torch.nn.ReLU()),
            ("pool",torch.nn.MaxPool2d(2))
        ])
        )

In [20]:
model = Net()

In [21]:
model

Net(
  (conv): Sequential(
    (conv1): Conv1d(3, 32, kernel_size=(3,), stride=(1,), padding=(1,))
    (relu1): ReLU()
    (pool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
)

In [23]:
model.conv.conv1

Conv1d(3, 32, kernel_size=(3,), stride=(1,), padding=(1,))

#### nn里面就是有Module和functional这两个，要需要有可学习参数的就可以直接调用nn.Xxx(nn.Linear, nn.Conv1d)
* 这些都是继承于nn.Module的
#### 不需要学习的，比如激活函数这些，就用functional就行，F.ReLU, F.softmax，F.sigmoid


#### optimizer.param_groups是一个长度为1的list,里面唯一的元素是一个dict,这个dict的key是各种的超参数，<br>比如lr,momentum这些，你可以根绝epoch的情况来自己手动改变他们

In [24]:
x

tensor([[-1.3288,  0.5707, -1.8041],
        [ 0.2446,  0.5754,  1.5342]])

* pow(2)就是平方的意思

In [25]:
x.pow(2)

tensor([[1.7656, 0.3257, 3.2548],
        [0.0598, 0.3311, 2.3537]])

In [26]:
x.size()

torch.Size([2, 3])

In [31]:
torch.zeros(*x.size())

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [32]:
import torch.utils.data as Data

In [40]:
x = torch.unsqueeze(torch.linspace(-1,1,1000), dim = 1)
x.shape

torch.Size([1000, 1])

* 每一行均值都0的正太分布

In [44]:
torch.normal(torch.zeros(*x.size())).shape

torch.Size([1000, 1])

In [45]:
y = x.pow(2) + 0.1 * torch.normal(torch.zeros(*x.size()))

In [48]:
from IPython.core.interactiveshell import InteractiveShell

InteractiveShell.ast_node_interactivity = 'all'

In [49]:
y.shape
x.shape

torch.Size([1000, 1])

torch.Size([1000, 1])

In [50]:
dataset = Data.TensorDataset(x,y)

In [51]:
dataset

#### 先有dataset然后再有dataloader

In [56]:
loader = Data.DataLoader(dataset = dataset, batch_size = 200, shuffle = True)

* 一个是x的，一个是y的

In [62]:
for batch in loader:
    print(batch[0].shape)
    print(batch[1].shape)
    break

torch.Size([200, 1])
torch.Size([200, 1])
