In [1]:
import torch
import torch.nn as nn
import torch.optim as optim

In [2]:
import numpy as np

### 1. numpy转torch张量

In [3]:
x = np.random.rand(2,3,5)
y = torch.from_numpy(x)

### 2. torch张量转numpy

In [4]:
x = torch.randn(2,3,5)
y = x.numpy()

### 3. torch张量放到cpu

In [5]:
x.cpu()

tensor([[[-1.8605,  0.5746,  1.0204, -0.3501,  0.6064],
         [-0.3705, -0.8260, -0.7749,  0.3132,  1.7654],
         [-0.7184, -1.4276, -1.9096, -1.0018, -0.2816]],

        [[-0.6227,  0.3883,  0.3244, -0.1308,  0.4275],
         [-1.0647, -0.9039, -0.2666,  0.8682, -0.8307],
         [ 1.2669,  1.3067, -1.2371,  0.1015,  0.5221]]])

### 4. torch张量放到第4号GPU

* z.cuda(4)#这个是对的

### 5. torch生成shape(B,C,T)的随机张量

In [6]:
b = 42
c = 39
t = 135
x = torch.rand(b,c,t)

### 6. torch生成shape(B,C,T)的全零张量

In [7]:
torch.zeros(b,c,t).shape

torch.Size([42, 39, 135])

### 7. torch生成shape(B,C,T)的全壹张量

In [8]:
torch.ones(b,c,t).shape

torch.Size([42, 39, 135])

### 8. torch生成输入39维输出128维的Linear层，并用随机数模拟输入

In [9]:
x = torch.rand(42, 39)
Linear = nn.Linear(39,128)
out = Linear(x)

### 9. torch生成输入39通道输出128通道的CNN层，并用随机数模拟输入

In [10]:
conv = nn.Conv1d(in_channels = 39, out_channels = 128, kernel_size = 3)
x = torch.rand(b,c,t)
out = conv(x)

### 10. torch生成输入39维输出128维的LSTM层，并用随机数模拟输入

In [39]:
x = torch.rand(t,b,c)#seq_len, batch_size, input_size
lstm = nn.LSTM(input_size = 39, hidden_size = 128, num_layers = 2)
out, hidden = lstm(x) 

In [40]:
out.shape#每一个时间步骤的最后一层隐藏层

torch.Size([135, 42, 128])

In [41]:
hidden[0].shape# 最后一个时间步骤的每一层的隐藏单元

torch.Size([2, 42, 128])

In [42]:
hidden[1].shape# 最后一个时间步骤的每一层的隐藏单元所对应的memory cell

torch.Size([2, 42, 128])

### 11. 请指出1x1卷积和Linear层的相同与不同之处

In [15]:
x = torch.randn(2,3,5)#batch,seq_len,feature_dim
linear = nn.Linear(5,128)
conv1 = nn.Conv1d(5,128,1)
out1 = linear(x)
out2 = conv1(x.transpose(1,2)).transpose(1,2)

In [16]:
out1.shape

torch.Size([2, 3, 128])

In [17]:
out2.shape

torch.Size([2, 3, 128])

* 差别应该就是如果想要达到相同的效果的话,要把x 的feature_dim 转到通道上来

### 12. LSTM层和CNN层的输入数据格式有什么区别

* LSTM的输入在没有设batch_first的时候是 seq_len, batch, input_dim(feature_dim)
* CNN的输入是, batch, in_channels(input_dim,feature_dim), seq_len

### 13. 用torch代码实现对张量x进行sigmoid操作
### 14. 用torch代码实现对张量x进行tanh操作
### 15. 用torch代码实现对张量x进行relu操作
### 16. 用torch代码实现对张量x进行softmax操作

In [18]:
x = torch.rand(2,3,4)
y = torch.tanh(x)
y = torch.sigmoid(x)
y = torch.relu(x)
y = torch.softmax(x, dim = 2)# 记得要加参数dim,这边我设置的x的第二维是时间，在时间上softmax
y

tensor([[[0.1547, 0.3182, 0.1835, 0.3436],
         [0.2761, 0.2437, 0.2189, 0.2612],
         [0.1767, 0.2928, 0.2389, 0.2916]],

        [[0.3066, 0.1594, 0.3824, 0.1517],
         [0.3110, 0.1921, 0.2171, 0.2799],
         [0.3992, 0.2119, 0.2079, 0.1811]]])

### 17. 用torch代码实现对张量x进行概率0.5的dropout操作

In [19]:
drop = nn.Dropout(p = 0.5)
y = drop(x)
y#drop的点的值就是0

tensor([[[0.0963, 0.0000, 0.4374, 1.6917],
         [0.0000, 1.0867, 0.0000, 1.2258],
         [0.8975, 0.0000, 1.5005, 1.8991]],

        [[0.0000, 0.0000, 1.9511, 0.1023],
         [0.0000, 0.5788, 0.0000, 0.0000],
         [1.6875, 0.0000, 0.3825, 0.0000]]])

### 18. 用torch代码实现张量的第2维和第1维交换位置
### 19. 用torch代码实现张量x转成long类型
### 20. 用torch代码实现张量x转成float类型
### 21. 用torch代码实现形状(2,3,5)的张量转成(2,15)的张量
### 22. 用torch代码实现将形状(2,3)的张量变为形状(2,3,1)的张量
### 23. 用torch代码实现将形状(2,3,1)的张量变为形状(2,3)的张量

In [20]:
y = x.permute(0,2,1)

In [21]:
y.shape

torch.Size([2, 4, 3])

In [22]:
x.long()
x.float()

tensor([[[0.0482, 0.7690, 0.2187, 0.8458],
         [0.6683, 0.5433, 0.4363, 0.6129],
         [0.4487, 0.9539, 0.7503, 0.9496]],

        [[0.7546, 0.1003, 0.9755, 0.0511],
         [0.7710, 0.2894, 0.4114, 0.6656],
         [0.8438, 0.2105, 0.1912, 0.0533]]])

In [23]:
x = torch.randn(2,3,5)
y = x.view(2,-1)
y.shape

torch.Size([2, 15])

In [24]:
x = torch.randn(2,3)
y = x.unsqueeze(2)
y.shape

torch.Size([2, 3, 1])

In [25]:
y.squeeze().shape

torch.Size([2, 3])

### 24. 用torch代码实现一个TDNN类，含有2个CNN层，扩张系数分别为2,4，其他参数自己定义，不得超过10行代码。


In [26]:
class TDNN(nn.Module):
    def __init__(self, idim, odim, hdim=192): # 128+64
        super(TDNN,self).__init__()
        # help(torch.nn.Conv1d.__init__)
        # torch.nn.Conv1d.__init__(self, in_channels, out_channels, kernel_size, stride=1, padding=0, dilation=1, groups=1, bias=True)
        # in_channels  输入通道数
        # out_channels 输出通道数
        # kernel_size  卷积核大小
        # padding      两边补零数
        # dilation     膨胀系数
        self.conv1 = torch.nn.Conv1d(in_channels=idim, out_channels=hdim, kernel_size=3, padding=2, dilation=2)
        self.conv2 = torch.nn.Conv1d(in_channels=hdim, out_channels=odim, kernel_size=3, padding=4, dilation=4)
    def forward(self, x):
        o1 = self.conv1(x).tanh()
        o2 = self.conv2(o1)
        o = o2.mean(dim = 2)
        return o

In [27]:
model = TDNN(39,128)
x = torch.randn(42,39,135)
y = model(x)
y.shape

torch.Size([42, 128])

### 25. 用torch代码实现一个Net类，含有1个CNN层和1个LSTM层，参数自己定义，要求注意forward时参数形状，不超过12行代码。


In [3]:
class Net(nn.Module):
    def __init__(self,feature_dim, hidden_dim, out_dim):
        super(Net,self).__init__()
        self.conv = nn.Conv1d(feature_dim, hidden_dim, kernel_size = 1)
        self.lstm = nn.LSTM(input_size = hidden_dim, hidden_size = out_dim, num_layers = 1)
    def forward(self,x):
        o1 = self.conv(x)# o1 - batch, hidden_dim, seq_len
        o2 = o1.permute(2,0,1)
        output, hidden = self.lstm(o2)
        return output

In [46]:
class Net_1(nn.Module):
    def __init__(self,feature_dim, hidden_dim, out_dim):
        super(Net_1,self).__init__()
        self.gru = nn.GRU(input_size = feature_dim, hidden_size = hidden_dim, num_layers = 2)
        self.conv = nn.Conv1d(hidden_dim, out_dim, kernel_size = 3)
    def forward(self,x):
        o1, hidden = self.gru(x)# o1 - time, batch, hidden_dim
        o2 = o1.permute(1,2,0)#o2 - batch, feature_dim, time
        output = self.conv(o2)
        o = output.max(dim = 2).values#时间维度上平均池化
        return o

In [47]:
model = Net_1(39,128,42)
x = torch.randn(135,5,39)#time, batch, feature_dim
y = model(x)
y.shape#(Batch,class_num) 

torch.Size([5, 42])

In [26]:
class Net_2(nn.Module):
    def __init__(self,feature_dim, hidden_dim, out_dim):
        super(Net_2,self).__init__()
        self.conv = nn.Conv1d(feature_dim, hidden_dim, kernel_size = 3)
        self.lstm = nn.LSTM(input_size = hidden_dim, hidden_size = out_dim, num_layers = 2)
    def forward(self,x):
        o1 = self.conv(x)# o1 - batch, hidden_dim, seq_len
        o2 = o1.permute(2,0,1)
        output, hidden = self.lstm(o2)#output是所有时间点最后一层隐藏层(time, batch, out_dim)
        o = output.mean(dim = 0)#时间维度上平均池化
        return o

In [27]:
model = Net_2(39,128,42)
x = torch.randn(5, 39, 135)#Batch, feature_dim, time
y = model(x)
y.shape#(Batch,class_num) 

torch.Size([5, 42])

In [48]:
xx = torch.rand(2,3,4)
xx.max(dim = 2, keepdim = True).values.shape


torch.Size([2, 3, 1])

### 26. 用一行代码创建一个Adam优化器，优化的参数为net中的全部参数

In [30]:
from torch.optim.lr_scheduler import LambdaLR
initial_lr = 0.008
optimizer_1 = torch.optim.Adam(model.parameters(), lr = initial_lr)
scheduler_1 = LambdaLR(optimizer_1, lr_lambda=lambda epoch:1/(epoch+1))

### 27. 用一行代码创建一个Adam优化器，优化的参数为net.cnn3中的参数

In [31]:
optimizer = torch.optim.Adam(model.conv.parameters(),lr = 0.0001)# 要大写

### 28. 用torch代码创建交叉熵损失对象，并用正确形状的随机数模拟输入


* 原来CrossEntropyLoss() 会把target变成ont-hot形式，我们现在例子的样本标签是[4]（从0开始计算）。那么转换成one-hot编码就是[0，0，0，0，1]，所以我们的最后也会变成一个5维的向量，并且不是该样本标签的数值为0

In [32]:
y = torch.rand(5, 42)
y_hat = torch.empty(5,dtype = torch.long).random_(42)#一个样本一个index - onehot, 需要是long数据类型.random_(42)是在0-41去选数字
loss_fn = nn.CrossEntropyLoss()
loss = loss_fn(y, y_hat)
loss

tensor(4.0420)

In [50]:
y = torch.empty(11).random_(5)
y

tensor([3., 0., 0., 4., 0., 2., 4., 1., 3., 1., 3.])

### 29. 用文字解释net.train()和net.eval()的作用

*  net.train表明我的模型现在处于训练的状态，这时候网络层里面设置的dropout是开启的，这样可以有效防止过拟合，还有就是batchnorm, 训练的时候我们的数据是一个batch一个batch去处理的，这时候batchnorm的u和sigma是可以算出来的, 所以其**use_global_stats**参数在训练时设置为false;model.eval(),把模型设置为测试状态，这时候它的所有的参数都是固定的，不能再变化，还有就是dropout这时候也不执行，由于测试阶段不是对batch进行处理而是一条一条数据，所以batchnorm用的u和sigma是基于全局的已经算好的u和sigma, **use_global_stats**参数设置为True,这也是我之前看的那篇论文Adaptive batch norm 所改善的地方，让batch norm 的u和sigma在测试的时候能动态生成

### 30. 用文字解释optimizer.step()和optimizer.zero_grad()的作用

* optimizer.zero_grad()是对计算的梯度进行清0，如果不清零的话前面算的梯度会累积
* optimizer.step()是用loss.backward()算好的梯度对optimizer里面所**管理的**参数进行更新

### 31. 用文字解释损失函数的backward()的作用

* 算出来的loss值是一个scalar,loss.backward(),就是在**计算图**中基于当前loss值的**这个节点**,从后往前把所有节点的梯度**通过链式法则**都算出来

In [34]:
from torch.autograd import Variable
x = Variable(torch.ones(2,2),requires_grad=True)
y = x + 1
z = (y*y+3).mean()
z.backward()

### 32. 指出下面代码错误的原因：

In [35]:
def train_network(net, data, label):
    net.train()
    predict = net(data)
    net.optimizer.step()
    net.optimizer.zero_grad()
    net.loss(predict, label).backward()

* 要先zero_grad()梯度清零以后,再去反向传播算出计算图中各个节点的梯度,然后再step()，也就是基于算出来的梯度对参数进行更新

### 33. 指出下面代码错误的原因并改正：

In [36]:
x = torch.randn(2,3,5)
y = torch.randn(2,3,5)
z = torch.matmul(x,y)

RuntimeError: Expected tensor to have size 5 at dimension 1, but got size 3 for argument #2 'batch2' (while checking arguments for bmm)

* matmul就是矩阵的相乘,要求两个数据要满足矩阵相乘的要求,也就是x的列维度要等于y的行维度

In [52]:
x = torch.randn(2,3,5)
y = torch.randn(2,5,3)
z = torch.matmul(x,y)

In [ ]:
z

### 34. 指出下面代码错误的原因并改正：

In [53]:
x = torch.randn(2,3,5)
y = torch.randn(2,3)
z = x * y

RuntimeError: The size of tensor a (5) must match the size of tensor b (3) at non-singleton dimension 2

* "*"的是进行数据的点乘，是把两个矩阵中相同对应位置的元素进行相乘，要求两个矩阵的维度个数要一样，且除维度值为1的(可以广播机制)其他维度的值要相同

In [54]:
x = torch.randn(2,3,5)
y = torch.randn(2,3,1)
z = x * y

In [55]:
x = torch.randn(2,3,5)
y = torch.randn(2,3,5)
z = x * y

In [56]:
x = torch.randn(2,3,5)
y = torch.randn(2,1,5)
z = x * y

In [57]:
x = torch.randn(2,3,5)
y = torch.randn(1,1,5)
z = x * y

### 35. 请文字说明DataSet中__getitem__的作用

* __getitem__是用来决定dataset每次要返回的每条样本是什么，在执行dataset[i]的时候，调用的就是对象中__getitem__这个方法，一般都是返回feature,label这样的一条样本数据

### 36. 请文字说明DataLoader中collate_fn的作用

* Collate_fn 就是一个自定义的对batch数据进行处理的函数，比如语音任务中一般就是在里面做一个Pad，然后把pad以后的数据返回

### 37. 请文字说明DataLoader中shuffle的作用

* shuffle 就是对数据进行一个打乱，防止模型对越靠后的数据越敏感的现象

### 38. 请用torch随机生成形状(B,C,T)的张量，并在时间维度上进行全局最大池化
### 39. 请用torch随机生成形状(B,C,T)的张量，并在时间维度上进行局部最大池化，核大小为3


In [58]:
x = torch.rand(42,39,135)

In [59]:
z = torch.max(x,dim = 2, keepdim = True)

In [60]:
z.values.shape

torch.Size([42, 39, 1])

In [61]:
x = torch.tensor([[[1,2],[2,3],[3,4]],[[5,6],[7,8],[9,10]]])

In [62]:
x

tensor([[[ 1,  2],
         [ 2,  3],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8],
         [ 9, 10]]])

In [63]:
x.shape

torch.Size([2, 3, 2])

In [64]:
z = torch.max(x,dim = 2, keepdim = True)

In [65]:
z.values

tensor([[[ 2],
         [ 3],
         [ 4]],

        [[ 6],
         [ 8],
         [10]]])

In [66]:
model = nn.MaxPool1d(kernel_size = x.shape[2])
z = model(x.float())
z

tensor([[[ 2.],
         [ 3.],
         [ 4.]],

        [[ 6.],
         [ 8.],
         [10.]]])

In [67]:
x = torch.rand(42,39,135)
model = nn.MaxPool1d(kernel_size = 3, stride = 1)#默认stride = kernel_size
z = model(x.float())
z.shape

torch.Size([42, 39, 133])

In [68]:
#F.max_pool1d(x, kernel_size=x.shape[2])

### 40. 请用torch随机生成形状(B,C,T)的张量，并在通道维度上进行全局最大池化
### 41. 请用torch随机生成形状(B,C,T)的张量，并在通道维度上进行局部最大池化，核大小为3

In [69]:
y = torch.max(x, dim = 1, keepdim = True) # keepdim中间没有下划线
y.values.shape#max以后记得要values

torch.Size([42, 1, 135])

In [70]:
x_1 = x.permute(0, 2, 1)
z = model(x_1.float())
u = z.permute(0,2,1)
u.shape

torch.Size([42, 37, 135])

### 42. 请用torch随机生成形状(2,3,5)和(2,3,7)两个张量，并拼接成(2,3,12)的张量
* 在哪一维拼起来dim就等于几,记得前面是一个list

In [80]:
x = torch.randn(2,3,5)
y = torch.randn(2,3,7)
z = torch.cat([x,y],dim = 2)
z.shape

torch.Size([2, 3, 12])

### 43. 请用torch随机生成两个形状(3,5)的张量，并堆叠成(2,3,5)的张量

In [78]:
x = torch.randn(3,5)
y = torch.randn(3,5)
z = torch.stack([x,y],dim = 0)
z.shape

torch.Size([2, 3, 5])

### 44. 请文字描述torch.nn.Sequential的作用

* 它是一个有序的容器，可以把多个首尾相连的层封装到里面来，注意，上一层数据的输出要符合下一层的输入，因为它是顺序传递的
* 而且sequential内部的forward的功能已经实现了，不需要自己再实现
* 当模型的前向计算为简单串联各个层的计算时

### 45. 请用numpy将语音x的长度从15000补零到长度16000

In [87]:
import numpy as np
max_frame = 16000
data = [np.random.rand(i,39) for i in range(1,43)]#B,C',T
pad_data = [np.pad(x,[(0,max_frame-len(x)),(0,0)]) for x in data]# [(第一个维度前面填充几位,第一个维度后面填充几位),(第二个维度...,..)]

In [88]:
np.array(pad_data).shape

(42, 16000, 39)

### 46. 请用librosa读取wav文件语音并转成16000采样率单通道语音

In [89]:
import librosa 
filename = librosa.example('nutcracker')
y, sr = librosa.load(filename, sr = 16000, mono=True)

### 47. 请用librosa去掉语音x中的静音
* https://zhuanlan.zhihu.com/p/44189287

In [94]:
x, index = librosa.effects.trim(y,20)#20是top_db的阈值 
#x是去除静音以后的序列,index是非静音段的开头索引和结束索引
print(type(index))
print(index)

<class 'numpy.ndarray'>
[  18944 1884160]


### 48. 请用librosa将语音x转为傅里叶谱spec，再逆变换回语音

In [95]:
spec = librosa.stft(y, n_fft=2048, window='hann')
y_ = librosa.istft(spec, window='hann')

In [97]:
print(type(y_))
print(y_.shape)

<class 'numpy.ndarray'>
(1917952,)


### 49. 请用soundfile将采样率fs的语音x保存到'out.wav'

In [99]:
import soundfile
fs = sr
soundfile.write('out.wav', y, fs)

### 50. 请用提取mfcc特征

In [108]:
import librosa
mfccs = librosa.feature.mfcc(y=y, sr=sr)
print(mfccs.shape)        # (40, 65)


(20, 3747)


In [109]:
import python_speech_features
wav_feature = python_speech_features.mfcc(y, sr)
wav_feature.shape
# '''
# signal - 需要用来计算特征的音频信号，应该是一个N*1的数组
# samplerate - 我们用来工作的信号的采样率
# winlen - 分析窗口的长度，按秒计，默认0.025s(25ms)
# winstep - 连续窗口之间的步长，按秒计，默认0.01s（10ms）
# numcep - 倒频谱返回的数量，默认13
# nfilt - 滤波器组的滤波器数量，默认26
# nfft - FFT的大小，默认512
# lowfreq - 梅尔滤波器的最低边缘，单位赫兹，默认为0
# highfreq - 梅尔滤波器的最高边缘，单位赫兹，默认为采样率/2
# preemph - 应用预加重过滤器和预加重过滤器的系数，0表示没有过滤器，默认0.97
# ceplifter - 将升降器应用于最终的倒谱系数。 0没有升降机。默认值为22。
# appendEnergy - 如果是true，则将第0个倒谱系数替换为总帧能量的对数。 
# '''

(11987, 13)

In [ ]:
# Beat tracking example
import librosa

# 1. Get the file path to an included audio example
filename = librosa.example('nutcracker')


# 2. Load the audio as a waveform `y`
#    Store the sampling rate as `sr`
y, sr = librosa.load(filename)

# 3. Run the default beat tracker
tempo, beat_frames = librosa.beat.beat_track(y=y, sr=sr)

print('Estimated tempo: {:.2f} beats per minute'.format(tempo))

# 4. Convert the frame indices of beat events into timestamps
beat_times = librosa.frames_to_time(beat_frames, sr=sr)